#!/bin/sh

OLD_CONFIG="$(pwd)/OLD_CONFIG"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

[ -d ./OLD_CONFIG ] ||
	mkdir ./OLD_CONFIG

cd .config ||
	exit 1

for i in *; do
    [ -d "$CONFIG/$i" ] && 
	    mv "$CONFIG/$i" "$OLD_CONFIG/$i" &&
	    echo "$CONFIG/$i -> $OLD_CONFIG/$i"
done
