#!/bin/sh

CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
SCRIPTS="$HOME/.local/bin"

cd .config ||
	exit 1

for i in *; do
    cp -r "$i" "$CONFIG/" &&
        echo "$(pwd)/$i -> $CONFIG/$i"
done

ln -sf "$CONFIG/zsh/zshrc" "$HOME/.zshrc"
ln -sf "$CONFIG/zsh/zprofile" "$HOME/.zprofile"

[ -d $CONFIG/zsh/pure ] ||
	git clone "https://github.com/sindresorhus/pure.git" "$CONFIG/zsh/pure"

cd ../.local/bin/ || 
    exit 1

cp -r ./* $SCRIPTS &&
    echo "Copied scripts to $SCRIPTS"
