export XDG_CURRENT_DESKTOP=dwm
export XDG_SESSION_TYPE=x11
export TERMINAL=st

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144 --output DP-1 --mode 1920x1080 --rate 60 --left-of HDMI-0
dunst &
unclutter &
picom &
dwmblocks &
xautolock -time 10 -locker slock &
xrdb "$XDG_CONFIG_HOME/X11/xresources/Xresources"
slockbg &
setxkbmap -option caps:escape

ssh-agent dwm
