# -*- conf -*-
font=JetBrainsMono Nerd Font :pixelsize=13:antialias=true:autohint=true
pad=4x4

[colors-dark]
foreground=d4d4d4
background=000000

regular0=1e1e1e
regular1=ff4242
regular2=608b4e
regular3=ffff66
regular4=569cd6
regular5=c678dd
regular6=56b6c2
regular7=d4d4d4

bright0=3c3c3c
bright1=ff5757
bright2=8c9b6d
bright3=ffff99
bright4=669ff6
bright5=cc77fd
bright6=6ec6c6
bright7=e0e0e0
