feh --bg-scale $HOME/.local/share/wallpapers/dotfiles-wallpapers/random/nord.png
dunst &
unclutter &
picom &
dwmblocks &
xautolock -time 10 -locker slock &
xrdb $XDG_CONFIG_HOME/X11/xresources/Xresources &
setxkbmap -option caps:escape

while :; do
	ssh-agent dwm
done
