feh --bg-scale --no-fehbg "$XDG_DATA_HOME/wallpapers/background.jpg"
dunst &
unclutter &
picom &
dwmblocks &
xautolock -time 10 -locker slock &
xrdb "$XDG_CONFIG_HOME/X11/xresources/Xresources"
slockbg &
setxkbmap -option caps:escape

while :; do
  ssh-agent dwm
done
