swayimg.text.hide()

swayimg.viewer.on_key("q", function()
  swayimg.exit()
end)
swayimg.viewer.on_key("Shift->", function()
  swayimg.viewer.rotate(90)
end)
swayimg.viewer.on_key("Shift-<", function()
  swayimg.viewer.rotate(270)
end)
swayimg.on_window_resize(function()
  swayimg.viewer.set_fix_scale("optimal")
end)
